#!/usr/bin/bash

echo "<span font_family='JetBrains Mono ExtraBold' foreground='#282828'> ${USER} </span>"
echo "<span font_family='JetBrains Mono ExtraBold' foreground='#282828'> ${USER} </span>"
echo ""

if [[ $(id -u) -eq 0 ]]; then
  exit 33
fi
